### ISSUE TITLE
Crashes in get location on all fragments with use of base fragment.

### ISSUE THREAD

**Issue by sagarkacha** [BirjuVachhani/locus-android#25]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3ABirjuVachhani
    
### Description

When we trying to use locus lib in viewpager with different fragments it gives me crashes and below is the debug log.

```
java.lang.IllegalStateException: Fragment LocationHelper{40f9948 (a28e8a4f-2db1-4ee2-8840-5546503ef983) LocationHelper} not attached to an activity.
        at androidx.fragment.app.Fragment.requireActivity(Fragment.java:716)
        at com.birjuvachhani.locationextension.LocationHelper.hasLocationPermission(LocationHelper.kt:182)
        at com.birjuvachhani.locationextension.LocationHelper.initPermissionModel(LocationHelper.kt:128)
        at com.birjuvachhani.locationextension.Locus.initLocationHelper(Locus.kt:150)
        at com.birjuvachhani.locationextension.Locus.getCurrentLocation(Locus.kt:94)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:896)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1679)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:536)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:170)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:612)
        at com.google.android.material.tabs.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2831)
        at com.google.android.material.tabs.TabLayout.dispatchTabSelected(TabLayout.java:1608)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1601)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1569)
        at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:1874)
        at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2059)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Steps to Reproduce

1. Initializing locus object on each fragment inside viewpager.
2. It crashes when the page offset limit of viewpager is default and total fragments are greater then that.

**Expected behavior:** It should not be crash.

**Actual behavior:** It crashes.

**Reproduces how often:** Every time when viewpager screen navigate.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by BirjuVachhani** [comment]
Fixed in release 3.0.0-alpha05
