### ISSUE TITLE
Crash with Failed resolution of: Lcom/google/android/gms/location/LocationRequest

### ISSUE THREAD

**Issue by JitainSharma** [BirjuVachhani/locus-android#39]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3ABirjuVachhani
    
### Description

Crash on some phones like: Honor Play [Android 9 OS].

### Steps to Reproduce

1. Start Locus.getCurrentLocation in app
2. Crash with java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationRequest;
3. Always crashes

**Expected behavior:** [What you expect to happen]
Should not crash and handle or uses the latest API

**Actual behavior:** [What actually happens]
Crash everytime

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Additional Information
Crash Log:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationRequest;
        at com.birjuvachhani.locus.ConfigurationKt.getDefaultRequest(Configuration.kt:68)
        at com.birjuvachhani.locus.Configuration.<init>(Configuration.kt:41)
        at com.birjuvachhani.locus.Locus.<clinit>(Locus.kt:84)
        at com.openapp.tusk.ui.base.BaseFragment.onDestroyView(BaseFragment.kt:106)
        at com.openapp.tusk.ui.view.main.SplashFragment.onDestroyView(Unknown Source:0)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2908)
        at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1344)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1264)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1504)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
        at android.app.Activity.performStart(Activity.java:7479)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationRequest" on path: DexPathList[[zip file "/data/app/com.openapp.tusk.beta-mADMueluT9dYZT2i1eUpzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.openapp.tusk.beta-mADMueluT9dYZT2i1eUpzg==/lib/arm64, /data/app/com.openapp.tusk.beta-mADMueluT9dYZT2i1eUpzg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2020-03-04 12:40:10.159 5240-5240/com.openapp.tusk.beta E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 41 more`

**Comment by BirjuVachhani** [comment]
@JitainSharma Did you make sure that you have added dependency for google location services?

```
implementation 'com.google.android.gms:play-services-location:17.0.0'
```
