### ISSUE TITLE
Unable to get current location

### ISSUE THREAD

**Issue by Damercy** [BirjuVachhani/locus-android#47]
**Bug**
App crashes when initializing Locus for getting current location in a fragment

**To Reproduce**
1. Initialize locus to get current location
```kotlin
 Locus.getCurrentLocation(requireContext()) { locusResult: LocusResult ->
    // Your task
}
```
2. Open the fragment that gets the current location using above api
3. App crashes

**Expected behavior**
Get current location

**Device info:**
 - Device: Lenovo K10 Note
 - OS: Android
 - Version: Pie (API 28)

**Additional context**
Here's the error:
```kotlin
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationRequest;
        at com.birjuvachhani.locus.ConfigurationKt.getDefaultRequest(Configuration.kt:68)
        at com.birjuvachhani.locus.Configuration.<init>(Configuration.kt:41)
        at com.birjuvachhani.locus.Locus.<clinit>(Locus.kt:84)
```

Last few lines:
```kotlin
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationRequest" on path: DexPathList[[zip file "/data/app/ai.microfinance.lyt-d39yxfzmfFCl5laJw1nNXg==/base.apk"],nativeLibraryDirectories=[/data/app/ai.microfinance.lyt-d39yxfzmfFCl5laJw1nNXg==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by Damercy** [comment]
Duplicate of #39
