### ISSUE TITLE
Errors in locat Pending Intent 

### ISSUE THREAD

**Issue by Siddhartha9536** [BirjuVachhani/locus-android#67]
java.lang.IllegalArgumentException: com.taskflo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:651)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:638)
        at com.birjuvachhani.locus.LocationBroadcastReceiver$Companion.getPendingIntent(LocationBroadcastReceiver.kt:41)
        at com.birjuvachhani.locus.LocationProvider$pendingIntent$2.invoke(LocationProvider.kt:40)
        at com.birjuvachhani.locus.LocationProvider$pendingIntent$2.invoke(LocationProvider.kt:37)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)

**Comment by BirjuVachhani** [comment]
@Siddhartha9536 I think has been fixed in the latest version of `Locus`. Which version are you using?

**Comment by BirjuVachhani** [comment]
Closing because of inactivity.
